### ISSUE TITLE
Refactor URL structure and REST api views

### ISSUE THREAD

**Issue by vegu** [fullctl/ixctl#32]
For ix-specific operations we want to determine the target exchange from the url path, similarly to how we do it for the organization.

This has implications for how REST api paths are routed:

- `/api/{org}/ix/{ix.id}/` replaced by `/api/ix/{org}/{ix}/`
- `/api/{org}/ix/{ix.id}/members/` replaced by `/api/member/{org}/{ix}/`
- `/api/{org}/ix/{ix.id}/members/add ` becomes a POST to `/api/member/{org}/{ix}/`
- `/api/{org}/ix/{ix.id}/members/delete` becomes a DELETE to `/api/member/{org}/{ix}/{member.id}`
- `/api/{org}/ix/{ix.id}/members/update` becomes a PUT to `/api/member/{org}/{ix}/{member.id}`

and so on ...

`ix` is a value that can be configure per exchange and defaults to an url friendly version of the exchange name. I

Need to add a `slug` field to the InternetExchange model, serializer and expose an UI element for updating it (PUT to `/api/{org}/ix/{ix.id}/`)

**Comment by egfrank** [comment]
Okay we have an initial PR for this, if you're able to pull and test that would be great!

https://github.com/fullctl/ixctl/pull/35

**Comment by egfrank** [comment]
@vegu , what do we want to do about the URLs for 
Network, RouteserverConfig, and PermissionRequest ? Right now I kept them the same but let me know if you'd like me to change that formatting.

**Comment by egfrank** [comment]
Still need to change the rsconf endpoint:

so the query will need to be changed
to query for the matching ix and then the rsconf with the name related to that ix (edited) 
/api/rsconf/{org_tag}/{ix_tag}/{name}

**Comment by egfrank** [comment]
Just noticed that changing the URLs changed the ability to select between different IXs.

In other words, now when we select different IXs on the `http://localhost:8000/org_tag/` main page, the selection of IX isn't propagating to the API calls for the Member and Routeserver listings

**Comment by egfrank** [comment]
This is almost done, I need to do a pass back through the frontend to confirm that all the buttons / URLs still work.

Note, that there were some fullctl changes that are necessary to test this branch:
https://github.com/fullctl/fullctl/pull/2
