### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by vegu** [fullctl/ixctl#39]
Look into tests that currently fail and figure if that's just cruft at this point to be removed, or fix them if not

**Comment by egfrank** [comment]
There are two PRs connected to this issue, one for ixctl to remove several tests and one for fullctl to add those tests back in.

@vegu It should be noted that the tests for `fullctl` are currently failing only on Python3.6 with the message 
`ERROR: Package 'fullctl' requires a different Python: 3.6.12 not in '<4.0,>=3.7'`. I'm not entirely sure if that's coming from the [Poetry requirement](https://github.com/fullctl/fullctl/blob/master/pyproject.toml) or somewhere else. But in general tests were passing for Python3.7 3.8 3.9 so I wanted to make the PR
https://github.com/fullctl/ixctl/pull/40
https://github.com/fullctl/fullctl/pull/6

**Comment by vegu** [comment]
Issues was this

```
 [tool.poetry.dependencies]
-python = "^3.7"
+python = "^3.6"
```

fixed and merged in fullctl/fullctl
